### ISSUE TITLE
Readme has wrong code, and other fixes

### ISSUE THREAD

**Issue by ianheggie** [Aaronmsv/PastejackingProtection#3]
Thanks for this - I was not aware of the issue previously.
1. the code in README code differs in behaviour from the pp.sh: use `cat -A <<< "$script"` so newlines are displayed
2. defensive coding - always put the constant first in bash tests: ie use `[[ y == "$execute" ]]` so it doesn't give a syntax error on input with punctuation like `-`
3. personal preference - I named the function 'x' (short for eXecute) - pp conflicts with package libpar-packer-perl

**Comment by Aaronmsv** [comment]
Thanks for the feedback!

> the code in README code differs in behaviour from the pp.sh: use cat -A <<< "$script" so newlines are displayed

Indeed, fixed it.

> defensive coding - always put the constant first in bash tests: ie use [[ y == "$execute" ]] so it doesn't give a syntax error on input with punctuation like -

I changed it, but I couldn't find information on this in the manual. It's the first time I hear this.

> personal preference - I named the function 'x' (short for eXecute) - pp conflicts with package libpar-packer-perl

Yeah, I chose pp because of PasteProtection. I'll leave it like this, but it's easy enough for people to rename it to what they want.

**Comment by ianheggie** [comment]
That was quick! FYI - I tripped over the constant thing last century in one of my own scripts, but recent bash doesn't have the same trouble unless you forget to enclose the expression in double quotes (it is still useful technique in OO languages like ruby). Anyway this is obviously done and dusted so I have closed it.
