### ISSUE TITLE
new alternative: bracketed paste mode in bash 4.4+ / readline 7+

### ISSUE THREAD

**Issue by rahiel** [Aaronmsv/PastejackingProtection#4]
Starting from readline version 7 there is a built in `enable-bracketed-paste` option. Turning that on, pasted commands do not execute automatically, they're only shown and the user can execute it by pressing enter. I tested with the demo's linked in your readme.

To enable it add `set enable-bracketed-paste on` to `~/.inputrc`.

**Comment by Aaronmsv** [comment]
Nice. Will add it to the readme. Thanks for letting me know!
